# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import platform_pb2 as platform__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in platform_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProfileAIServiceStub(object):
    """-------- Python-side AI services --------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateGitHubSummary = channel.unary_unary(
                '/jobplatform.ProfileAIService/GenerateGitHubSummary',
                request_serializer=platform__pb2.GitHubSummaryRequest.SerializeToString,
                response_deserializer=platform__pb2.GitHubSummaryResponse.FromString,
                _registered_method=True)
        self.UploadResume = channel.unary_unary(
                '/jobplatform.ProfileAIService/UploadResume',
                request_serializer=platform__pb2.ResumeUploadRequest.SerializeToString,
                response_deserializer=platform__pb2.ResumeUploadResponse.FromString,
                _registered_method=True)
        self.UpdateResume = channel.unary_unary(
                '/jobplatform.ProfileAIService/UpdateResume',
                request_serializer=platform__pb2.UpdateResumeRequest.SerializeToString,
                response_deserializer=platform__pb2.ResumeResponse.FromString,
                _registered_method=True)
        self.GenerateResume = channel.unary_unary(
                '/jobplatform.ProfileAIService/GenerateResume',
                request_serializer=platform__pb2.GenerateResumeRequest.SerializeToString,
                response_deserializer=platform__pb2.ResumeResponse.FromString,
                _registered_method=True)


class ProfileAIServiceServicer(object):
    """-------- Python-side AI services --------
    """

    def GenerateGitHubSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadResume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateResume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateResume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProfileAIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateGitHubSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateGitHubSummary,
                    request_deserializer=platform__pb2.GitHubSummaryRequest.FromString,
                    response_serializer=platform__pb2.GitHubSummaryResponse.SerializeToString,
            ),
            'UploadResume': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadResume,
                    request_deserializer=platform__pb2.ResumeUploadRequest.FromString,
                    response_serializer=platform__pb2.ResumeUploadResponse.SerializeToString,
            ),
            'UpdateResume': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateResume,
                    request_deserializer=platform__pb2.UpdateResumeRequest.FromString,
                    response_serializer=platform__pb2.ResumeResponse.SerializeToString,
            ),
            'GenerateResume': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateResume,
                    request_deserializer=platform__pb2.GenerateResumeRequest.FromString,
                    response_serializer=platform__pb2.ResumeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jobplatform.ProfileAIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jobplatform.ProfileAIService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProfileAIService(object):
    """-------- Python-side AI services --------
    """

    @staticmethod
    def GenerateGitHubSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jobplatform.ProfileAIService/GenerateGitHubSummary',
            platform__pb2.GitHubSummaryRequest.SerializeToString,
            platform__pb2.GitHubSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadResume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jobplatform.ProfileAIService/UploadResume',
            platform__pb2.ResumeUploadRequest.SerializeToString,
            platform__pb2.ResumeUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateResume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jobplatform.ProfileAIService/UpdateResume',
            platform__pb2.UpdateResumeRequest.SerializeToString,
            platform__pb2.ResumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateResume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jobplatform.ProfileAIService/GenerateResume',
            platform__pb2.GenerateResumeRequest.SerializeToString,
            platform__pb2.ResumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class JobPlatformServiceStub(object):
    """-------- Node-side platform services --------
    (future, not required now)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUserProfile = channel.unary_unary(
                '/jobplatform.JobPlatformService/GetUserProfile',
                request_serializer=platform__pb2.UserProfileRequest.SerializeToString,
                response_deserializer=platform__pb2.UserProfileResponse.FromString,
                _registered_method=True)
        self.GetJob = channel.unary_unary(
                '/jobplatform.JobPlatformService/GetJob',
                request_serializer=platform__pb2.JobRequest.SerializeToString,
                response_deserializer=platform__pb2.JobResponse.FromString,
                _registered_method=True)


class JobPlatformServiceServicer(object):
    """-------- Node-side platform services --------
    (future, not required now)
    """

    def GetUserProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JobPlatformServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUserProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserProfile,
                    request_deserializer=platform__pb2.UserProfileRequest.FromString,
                    response_serializer=platform__pb2.UserProfileResponse.SerializeToString,
            ),
            'GetJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJob,
                    request_deserializer=platform__pb2.JobRequest.FromString,
                    response_serializer=platform__pb2.JobResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jobplatform.JobPlatformService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jobplatform.JobPlatformService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class JobPlatformService(object):
    """-------- Node-side platform services --------
    (future, not required now)
    """

    @staticmethod
    def GetUserProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jobplatform.JobPlatformService/GetUserProfile',
            platform__pb2.UserProfileRequest.SerializeToString,
            platform__pb2.UserProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jobplatform.JobPlatformService/GetJob',
            platform__pb2.JobRequest.SerializeToString,
            platform__pb2.JobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
